"""Discoverable registry for external CSTA baseline arms.

The runner historically grew faster than the documentation.  This manifest is
the stable map from a method name to its implementation file, conceptual family,
and intended runner entrypoint.  Keep it synchronized with
``scripts/run_external_baselines_phase1.py::METHOD_INFO``.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List


@dataclass(frozen=True)
class ExternalBaselineSpec:
    name: str
    phase: str
    family: str
    source_space: str
    label_mode: str
    budget_matched: bool
    implementation_status: str
    code_symbol: str
    code_file: str
    runner: str
    notes: str


EXTERNAL_BASELINE_CATALOG: Dict[str, ExternalBaselineSpec] = {
    "no_aug": ExternalBaselineSpec(
        name="no_aug",
        phase="phase1",
        family="control",
        source_space="none",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native",
        code_symbol="runner no_aug branch",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms no_aug",
        notes="Backbone-only reference with no synthetic samples.",
    ),
    "raw_aug_jitter": ExternalBaselineSpec(
        name="raw_aug_jitter",
        phase="phase1",
        family="raw_time",
        source_space="raw_time",
        label_mode="hard",
        budget_matched=True,
        implementation_status="tsaug_adapter",
        code_symbol="raw_aug_jitter",
        code_file="utils/external_baselines.py",
        runner="run_external_baselines_phase1.py --arms raw_aug_jitter",
        notes="Gaussian noise via tsaug.AddNoise.",
    ),
    "raw_aug_scaling": ExternalBaselineSpec(
        name="raw_aug_scaling",
        phase="phase1",
        family="raw_time",
        source_space="raw_time",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native",
        code_symbol="raw_aug_scaling",
        code_file="utils/external_baselines.py",
        runner="run_external_baselines_phase1.py --arms raw_aug_scaling",
        notes="Amplitude scaling, x_aug = a*x, a sampled uniformly.",
    ),
    "raw_aug_timewarp": ExternalBaselineSpec(
        name="raw_aug_timewarp",
        phase="phase1",
        family="raw_time",
        source_space="raw_time",
        label_mode="hard",
        budget_matched=True,
        implementation_status="tsaug_adapter",
        code_symbol="raw_aug_timewarp",
        code_file="utils/external_baselines.py",
        runner="run_external_baselines_phase1.py --arms raw_aug_timewarp",
        notes="Global time warping via tsaug.TimeWarp.",
    ),
    "raw_aug_magnitude_warping": ExternalBaselineSpec(
        name="raw_aug_magnitude_warping",
        phase="phase2",
        family="raw_time",
        source_space="raw_time",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native",
        code_symbol="raw_aug_magnitude_warping",
        code_file="utils/external_baselines.py",
        runner="run_external_baselines_phase1.py --arms raw_aug_magnitude_warping",
        notes="Per-channel cubic-spline magnitude curve.",
    ),
    "raw_aug_window_warping": ExternalBaselineSpec(
        name="raw_aug_window_warping",
        phase="phase2",
        family="raw_time",
        source_space="raw_time",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native",
        code_symbol="raw_aug_window_warping",
        code_file="utils/external_baselines.py",
        runner="run_external_baselines_phase1.py --arms raw_aug_window_warping",
        notes="Warp a local time window and resample to original length.",
    ),
    "raw_aug_window_slicing": ExternalBaselineSpec(
        name="raw_aug_window_slicing",
        phase="phase2",
        family="raw_time",
        source_space="raw_time",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native",
        code_symbol="raw_aug_window_slicing",
        code_file="utils/external_baselines.py",
        runner="run_external_baselines_phase1.py --arms raw_aug_window_slicing",
        notes="Keep a random continuous window and resample to original length.",
    ),
    "raw_mixup": ExternalBaselineSpec(
        name="raw_mixup",
        phase="phase1",
        family="vicinal",
        source_space="raw_mixup",
        label_mode="soft",
        budget_matched=True,
        implementation_status="native",
        code_symbol="raw_mixup",
        code_file="utils/external_baselines.py",
        runner="run_external_baselines_phase1.py --arms raw_mixup",
        notes="Input-space Mixup with soft-label CE; currently ResNet1D only.",
    ),
    "raw_smote_flatten_balanced": ExternalBaselineSpec(
        name="raw_smote_flatten_balanced",
        phase="phase1",
        family="vicinal",
        source_space="flattened_raw",
        label_mode="hard",
        budget_matched=False,
        implementation_status="imbalanced_learn_adapter",
        code_symbol="raw_smote_flatten_balanced",
        code_file="utils/external_baselines.py",
        runner="run_external_baselines_phase1.py --arms raw_smote_flatten_balanced",
        notes="Class-balancing SMOTE on flattened [C*T]; not multiplier matched.",
    ),
    "dba_sameclass": ExternalBaselineSpec(
        name="dba_sameclass",
        phase="phase1",
        family="dtw_barycenter",
        source_space="dtw_barycenter",
        label_mode="hard",
        budget_matched=True,
        implementation_status="tslearn_adapter",
        code_symbol="dba_sameclass",
        code_file="utils/external_baselines.py",
        runner="run_external_baselines_phase1.py --arms dba_sameclass",
        notes="Same-class DTW barycenter averaging via tslearn.",
    ),
    "wdba_sameclass": ExternalBaselineSpec(
        name="wdba_sameclass",
        phase="phase2",
        family="dtw_barycenter",
        source_space="dtw_barycenter",
        label_mode="hard",
        budget_matched=True,
        implementation_status="tslearn_adapter",
        code_symbol="wdba_sameclass",
        code_file="utils/external_baselines.py",
        runner="run_external_baselines_phase1.py --arms wdba_sameclass",
        notes="Anchor-weighted same-class DBA with DTW-distance softmax weights.",
    ),
    "spawner_sameclass_style": ExternalBaselineSpec(
        name="spawner_sameclass_style",
        phase="phase2",
        family="dtw_pattern_mix",
        source_space="dtw_pattern_mix",
        label_mode="hard",
        budget_matched=True,
        implementation_status="cleanroom_style",
        code_symbol="spawner_sameclass_style",
        code_file="utils/external_baselines.py",
        runner="run_external_baselines_phase1.py --arms spawner_sameclass_style",
        notes="SPAWNER-style DTW-aligned same-class pattern mixing.",
    ),
    "rgw_sameclass": ExternalBaselineSpec(
        name="rgw_sameclass",
        phase="phase2",
        family="dtw_guided_warp",
        source_space="dtw_guided_warp",
        label_mode="hard",
        budget_matched=True,
        implementation_status="cleanroom_adapter",
        code_symbol="rgw_sameclass",
        code_file="utils/external_baselines.py",
        runner="run_external_baselines_phase1.py --arms rgw_sameclass",
        notes="Random Guided Warping: random same-class prototype + DTW path warp.",
    ),
    "dgw_sameclass": ExternalBaselineSpec(
        name="dgw_sameclass",
        phase="phase2",
        family="dtw_guided_warp",
        source_space="dtw_guided_warp",
        label_mode="hard",
        budget_matched=True,
        implementation_status="cleanroom_adapter",
        code_symbol="dgw_sameclass",
        code_file="utils/external_baselines.py",
        runner="run_external_baselines_phase1.py --arms dgw_sameclass",
        notes="Discriminative Guided Warping: positive/negative prototype scoring + DTW path warp.",
    ),
    "jobda_cleanroom": ExternalBaselineSpec(
        name="jobda_cleanroom",
        phase="phase2",
        family="supervised_augmentation",
        source_space="raw_time_tsw",
        label_mode="joint_hard",
        budget_matched=False,
        implementation_status="cleanroom",
        code_symbol="jobda_cleanroom_augmented_set",
        code_file="utils/external_baselines.py",
        runner="run_external_baselines_phase1.py --arms jobda_cleanroom",
        notes="JobDA-style TSW transforms with joint labels; no confirmed official code found.",
    ),
    "random_cov_state": ExternalBaselineSpec(
        name="random_cov_state",
        phase="phase1",
        family="covariance_state",
        source_space="covariance_state",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native",
        code_symbol="random_cov_state",
        code_file="utils/external_baselines.py",
        runner="run_external_baselines_phase1.py --arms random_cov_state",
        notes="Random unit direction in Log-Euclidean covariance-state space.",
    ),
    "pca_cov_state": ExternalBaselineSpec(
        name="pca_cov_state",
        phase="phase1",
        family="covariance_state",
        source_space="covariance_state",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native",
        code_symbol="pca_cov_state",
        code_file="utils/external_baselines.py",
        runner="run_external_baselines_phase1.py --arms pca_cov_state",
        notes="Top PCA directions in train-only covariance-state space.",
    ),
    "csta_top1_current": ExternalBaselineSpec(
        name="csta_top1_current",
        phase="phase1",
        family="csta_pia",
        source_space="covariance_template",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="_run_csta_method + run_act_pilot.py",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms csta_top1_current",
        notes="CSTA/PIA top1 policy routed through run_act_pilot.py.",
    ),
    "csta_group_template_top": ExternalBaselineSpec(
        name="csta_group_template_top",
        phase="phase1",
        family="csta_pia",
        source_space="covariance_template",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="_run_csta_method + run_act_pilot.py",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms csta_group_template_top",
        notes="CSTA group-top neighborhood-consensus extension.",
    ),
    "csta_topk_softmax_tau_0.05": ExternalBaselineSpec(
        name="csta_topk_softmax_tau_0.05",
        phase="csta_sampling",
        family="csta_pia",
        source_space="covariance_template",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="_run_csta_method + run_act_pilot.py",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms csta_topk_softmax_tau_0.05",
        notes="PIA top-K softmax activation policy with tau=0.05.",
    ),
    "csta_topk_softmax_tau_0.10": ExternalBaselineSpec(
        name="csta_topk_softmax_tau_0.10",
        phase="csta_sampling",
        family="csta_pia",
        source_space="covariance_template",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="_run_csta_method + run_act_pilot.py",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms csta_topk_softmax_tau_0.10",
        notes="PIA top-K softmax activation policy with tau=0.10.",
    ),
    "csta_topk_softmax_tau_0.20": ExternalBaselineSpec(
        name="csta_topk_softmax_tau_0.20",
        phase="csta_sampling",
        family="csta_pia",
        source_space="covariance_template",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="_run_csta_method + run_act_pilot.py",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms csta_topk_softmax_tau_0.20",
        notes="PIA top-K softmax activation policy with tau=0.20.",
    ),
    "csta_topk_uniform_top5": ExternalBaselineSpec(
        name="csta_topk_uniform_top5",
        phase="csta_sampling",
        family="csta_pia",
        source_space="covariance_template",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="_run_csta_method + run_act_pilot.py",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms csta_topk_uniform_top5",
        notes="Current strongest primary PIA sampling policy.",
    ),
    "manifold_mixup": ExternalBaselineSpec(
        name="manifold_mixup",
        phase="phase3",
        family="hidden_state",
        source_space="hidden_state",
        label_mode="soft",
        budget_matched=False,
        implementation_status="native_training_strategy",
        code_symbol="fit_manifold_mixup_backbone",
        code_file="utils/backbone_trainers.py",
        runner="run_external_baselines_phase1.py --arms manifold_mixup",
        notes="Hidden-state Mixup training strategy; ResNet1D only.",
    ),
    "timevae_classwise_optional": ExternalBaselineSpec(
        name="timevae_classwise_optional",
        phase="phase3",
        family="generative_model",
        source_space="generative_model",
        label_mode="hard",
        budget_matched=False,
        implementation_status="pytorch_translation_adapter",
        code_symbol="timevae_classwise_optional",
        code_file="utils/external_baselines.py",
        runner="run_external_baselines_phase1.py --arms timevae_classwise_optional",
        notes="Classwise TimeVAE-style generator; records target/actual ratio and is not yet full official TimeVAE parity.",
    ),
}


def catalog_rows() -> List[ExternalBaselineSpec]:
    return [EXTERNAL_BASELINE_CATALOG[name] for name in sorted(EXTERNAL_BASELINE_CATALOG)]


def names_by_phase(phase: str) -> List[str]:
    return sorted(name for name, spec in EXTERNAL_BASELINE_CATALOG.items() if spec.phase == phase)


def names_by_family(family: str) -> List[str]:
    return sorted(name for name, spec in EXTERNAL_BASELINE_CATALOG.items() if spec.family == family)
