"""Discoverable catalog for external CSTA baseline arms.

The runtime source of truth is ``utils.external_runner_registry.METHOD_INFO``.
This manifest is a documentation/search layer: it stores conceptual family,
implementation location, and notes, then projects runtime fields such as
``source_space``, ``label_mode``, and ``budget_matched`` from the registry below.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Dict, List

from utils.external_runner_registry import METHOD_INFO


@dataclass(frozen=True)
class ExternalBaselineSpec:
    name: str
    phase: str
    family: str
    method_type: str  # "external_baseline" | "csta_internal" | "csta_control"
    source_space: str
    label_mode: str
    budget_matched: bool
    implementation_status: str
    code_symbol: str
    code_file: str
    runner: str
    notes: str


EXTERNAL_BASELINE_CATALOG: Dict[str, ExternalBaselineSpec] = {
    "no_aug": ExternalBaselineSpec(
        name="no_aug",
        phase="phase1",
        family="control",
        method_type="csta_control",
        source_space="none",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native",
        code_symbol="runner no_aug branch",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms no_aug",
        notes="Backbone-only reference with no synthetic samples.",
    ),
    "raw_aug_jitter": ExternalBaselineSpec(
        name="raw_aug_jitter",
        phase="phase1",
        family="raw_time",
        method_type="external_baseline",
        source_space="raw_time",
        label_mode="hard",
        budget_matched=True,
        implementation_status="tsaug_adapter",
        code_symbol="raw_aug_jitter",
        code_file="utils/external_baseline_methods/raw_jitter.py",
        runner="run_external_baselines_phase1.py --arms raw_aug_jitter",
        notes="Gaussian noise via tsaug.AddNoise.",
    ),
    "raw_aug_scaling": ExternalBaselineSpec(
        name="raw_aug_scaling",
        phase="phase1",
        family="raw_time",
        method_type="external_baseline",
        source_space="raw_time",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native",
        code_symbol="raw_aug_scaling",
        code_file="utils/external_baseline_methods/raw_scaling.py",
        runner="run_external_baselines_phase1.py --arms raw_aug_scaling",
        notes="Amplitude scaling, x_aug = a*x, a sampled uniformly.",
    ),
    "raw_aug_timewarp": ExternalBaselineSpec(
        name="raw_aug_timewarp",
        phase="phase1",
        family="raw_time",
        method_type="external_baseline",
        source_space="raw_time",
        label_mode="hard",
        budget_matched=True,
        implementation_status="tsaug_adapter",
        code_symbol="raw_aug_timewarp",
        code_file="utils/external_baseline_methods/raw_timewarp.py",
        runner="run_external_baselines_phase1.py --arms raw_aug_timewarp",
        notes="Global time warping via tsaug.TimeWarp.",
    ),
    "raw_aug_magnitude_warping": ExternalBaselineSpec(
        name="raw_aug_magnitude_warping",
        phase="phase2",
        family="raw_time",
        method_type="external_baseline",
        source_space="raw_time",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native",
        code_symbol="raw_aug_magnitude_warping",
        code_file="utils/external_baseline_methods/raw_magnitude_warping.py",
        runner="run_external_baselines_phase1.py --arms raw_aug_magnitude_warping",
        notes="Per-channel cubic-spline magnitude curve.",
    ),
    "raw_aug_window_warping": ExternalBaselineSpec(
        name="raw_aug_window_warping",
        phase="phase2",
        family="raw_time",
        method_type="external_baseline",
        source_space="raw_time",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native",
        code_symbol="raw_aug_window_warping",
        code_file="utils/external_baseline_methods/raw_window_warping.py",
        runner="run_external_baselines_phase1.py --arms raw_aug_window_warping",
        notes="Warp a local time window and resample to original length.",
    ),
    "raw_aug_window_slicing": ExternalBaselineSpec(
        name="raw_aug_window_slicing",
        phase="phase2",
        family="raw_time",
        method_type="external_baseline",
        source_space="raw_time",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native",
        code_symbol="raw_aug_window_slicing",
        code_file="utils/external_baseline_methods/raw_window_slicing.py",
        runner="run_external_baselines_phase1.py --arms raw_aug_window_slicing",
        notes="Keep a random continuous window and resample to original length.",
    ),
    "raw_mixup": ExternalBaselineSpec(
        name="raw_mixup",
        phase="phase1",
        family="vicinal",
        method_type="external_baseline",
        source_space="raw_mixup",
        label_mode="soft",
        budget_matched=True,
        implementation_status="native",
        code_symbol="raw_mixup",
        code_file="utils/external_baseline_methods/raw_mixup.py",
        runner="run_external_baselines_phase1.py --arms raw_mixup",
        notes="Input-space Mixup with soft-label CE; currently ResNet1D only.",
    ),
    "raw_smote_flatten_balanced": ExternalBaselineSpec(
        name="raw_smote_flatten_balanced",
        phase="phase1",
        family="vicinal",
        method_type="external_baseline",
        source_space="flattened_raw",
        label_mode="hard",
        budget_matched=False,
        implementation_status="imbalanced_learn_adapter",
        code_symbol="raw_smote_flatten_balanced",
        code_file="utils/external_baseline_methods/smote.py",
        runner="run_external_baselines_phase1.py --arms raw_smote_flatten_balanced",
        notes="Class-balancing SMOTE on flattened [C*T]; not multiplier matched.",
    ),
    "dba_sameclass": ExternalBaselineSpec(
        name="dba_sameclass",
        phase="phase1",
        family="dtw_barycenter",
        method_type="external_baseline",
        source_space="dtw_barycenter",
        label_mode="hard",
        budget_matched=True,
        implementation_status="tslearn_adapter",
        code_symbol="dba_sameclass",
        code_file="utils/external_baseline_methods/dba.py",
        runner="run_external_baselines_phase1.py --arms dba_sameclass",
        notes="Same-class DTW barycenter averaging via tslearn.",
    ),
    "wdba_sameclass": ExternalBaselineSpec(
        name="wdba_sameclass",
        phase="phase2",
        family="dtw_barycenter",
        method_type="external_baseline",
        source_space="dtw_barycenter",
        label_mode="hard",
        budget_matched=True,
        implementation_status="tslearn_adapter",
        code_symbol="wdba_sameclass",
        code_file="utils/external_baseline_methods/wdba.py",
        runner="run_external_baselines_phase1.py --arms wdba_sameclass",
        notes="Anchor-weighted same-class DBA with DTW-distance softmax weights.",
    ),
    "spawner_sameclass_style": ExternalBaselineSpec(
        name="spawner_sameclass_style",
        phase="phase2",
        family="dtw_pattern_mix",
        method_type="external_baseline",
        source_space="dtw_pattern_mix",
        label_mode="hard",
        budget_matched=True,
        implementation_status="cleanroom_style",
        code_symbol="spawner_sameclass_style",
        code_file="utils/external_baseline_methods/spawner.py",
        runner="run_external_baselines_phase1.py --arms spawner_sameclass_style",
        notes="SPAWNER-style DTW-aligned same-class pattern mixing.",
    ),
    "rgw_sameclass": ExternalBaselineSpec(
        name="rgw_sameclass",
        phase="phase2",
        family="dtw_guided_warp",
        method_type="external_baseline",
        source_space="dtw_guided_warp",
        label_mode="hard",
        budget_matched=True,
        implementation_status="cleanroom_adapter",
        code_symbol="rgw_sameclass",
        code_file="utils/external_baseline_methods/rgw.py",
        runner="run_external_baselines_phase1.py --arms rgw_sameclass",
        notes="Random Guided Warping: random same-class prototype + DTW path warp.",
    ),
    "dgw_sameclass": ExternalBaselineSpec(
        name="dgw_sameclass",
        phase="phase2",
        family="dtw_guided_warp",
        method_type="external_baseline",
        source_space="dtw_guided_warp",
        label_mode="hard",
        budget_matched=True,
        implementation_status="cleanroom_adapter",
        code_symbol="dgw_sameclass",
        code_file="utils/external_baseline_methods/dgw.py",
        runner="run_external_baselines_phase1.py --arms dgw_sameclass",
        notes="Discriminative Guided Warping: positive/negative prototype scoring + DTW path warp.",
    ),
    "jobda_cleanroom": ExternalBaselineSpec(
        name="jobda_cleanroom",
        phase="phase2",
        family="supervised_augmentation",
        method_type="external_baseline",
        source_space="raw_time_tsw",
        label_mode="joint_hard",
        budget_matched=False,
        implementation_status="cleanroom",
        code_symbol="jobda_cleanroom_augmented_set",
        code_file="utils/external_baseline_methods/jobda.py",
        runner="run_external_baselines_phase1.py --arms jobda_cleanroom",
        notes="JobDA-style TSW transforms with joint labels; no confirmed official code found.",
    ),
    "random_cov_state": ExternalBaselineSpec(
        name="random_cov_state",
        phase="phase1",
        family="covariance_state",
        method_type="csta_control",
        source_space="covariance_state",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native",
        code_symbol="random_cov_state",
        code_file="utils/external_baseline_methods/random_cov_state.py",
        runner="run_external_baselines_phase1.py --arms random_cov_state",
        notes="Random unit direction in Log-Euclidean covariance-state space.",
    ),
    "pca_cov_state": ExternalBaselineSpec(
        name="pca_cov_state",
        phase="phase1",
        family="covariance_state",
        method_type="csta_control",
        source_space="covariance_state",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native",
        code_symbol="pca_cov_state",
        code_file="utils/external_baseline_methods/pca_cov_state.py",
        runner="run_external_baselines_phase1.py --arms pca_cov_state",
        notes="Top PCA directions in train-only covariance-state space.",
    ),
    "csta_top1_current": ExternalBaselineSpec(
        name="csta_top1_current",
        phase="phase1",
        family="csta_pia",
        method_type="csta_internal",
        source_space="covariance_template",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="_run_csta_method + run_act_pilot.py",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms csta_top1_current",
        notes="CSTA/PIA top1 policy routed through run_act_pilot.py.",
    ),
    "csta_group_template_top": ExternalBaselineSpec(
        name="csta_group_template_top",
        phase="phase1",
        family="csta_pia",
        method_type="csta_internal",
        source_space="covariance_template",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="_run_csta_method + run_act_pilot.py",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms csta_group_template_top",
        notes="CSTA group-top neighborhood-consensus extension.",
    ),
    "csta_topk_softmax_tau_0.05": ExternalBaselineSpec(
        name="csta_topk_softmax_tau_0.05",
        phase="csta_sampling",
        family="csta_pia",
        method_type="csta_internal",
        source_space="covariance_template",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="_run_csta_method + run_act_pilot.py",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms csta_topk_softmax_tau_0.05",
        notes="PIA top-K softmax activation policy with tau=0.05.",
    ),
    "csta_topk_softmax_tau_0.10": ExternalBaselineSpec(
        name="csta_topk_softmax_tau_0.10",
        phase="csta_sampling",
        family="csta_pia",
        method_type="csta_internal",
        source_space="covariance_template",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="_run_csta_method + run_act_pilot.py",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms csta_topk_softmax_tau_0.10",
        notes="PIA top-K softmax activation policy with tau=0.10.",
    ),
    "csta_topk_softmax_tau_0.20": ExternalBaselineSpec(
        name="csta_topk_softmax_tau_0.20",
        phase="csta_sampling",
        family="csta_pia",
        method_type="csta_internal",
        source_space="covariance_template",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="_run_csta_method + run_act_pilot.py",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms csta_topk_softmax_tau_0.20",
        notes="PIA top-K softmax activation policy with tau=0.20.",
    ),
    "csta_topk_uniform_top5": ExternalBaselineSpec(
        name="csta_topk_uniform_top5",
        phase="csta_sampling",
        family="csta_pia",
        method_type="csta_internal",
        source_space="covariance_template",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="_run_csta_method + run_act_pilot.py",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms csta_topk_uniform_top5",
        notes="Current strongest primary PIA sampling policy.",
    ),
    "csta_template_random_within_bank": ExternalBaselineSpec(
        name="csta_template_random_within_bank",
        phase="direction_specificity",
        family="csta_pia",
        method_type="csta_internal",
        source_space="covariance_template",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="_run_csta_method + run_act_pilot.py --template-selection random",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms csta_template_random_within_bank",
        notes="PIA bank-random control: sample random template directions from the train-only TELM2 dictionary.",
    ),
    "csta_fv_filter_top5": ExternalBaselineSpec(
        name="csta_fv_filter_top5",
        phase="csta_selector",
        family="csta_pia",
        method_type="csta_internal",
        source_space="covariance_template",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="_run_csta_method + run_act_pilot.py",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms csta_fv_filter_top5",
        notes="Pre-bridge feasibility-filtered high-response PIA selector.",
    ),
    "csta_fv_score_top5": ExternalBaselineSpec(
        name="csta_fv_score_top5",
        phase="csta_selector",
        family="csta_pia",
        method_type="csta_internal",
        source_space="covariance_template",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="_run_csta_method + run_act_pilot.py",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms csta_fv_score_top5",
        notes="Pre-bridge fidelity-variety scored PIA selector.",
    ),
    "csta_random_feasible_selector": ExternalBaselineSpec(
        name="csta_random_feasible_selector",
        phase="csta_selector",
        family="csta_pia",
        method_type="csta_internal",
        source_space="covariance_template",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="_run_csta_method + run_act_pilot.py",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms csta_random_feasible_selector",
        notes="Feasible-only random control for testing whether candidate quality ranking matters.",
    ),
    "csta_topk_uniform_top5_ao_fisher": ExternalBaselineSpec(
        name="csta_topk_uniform_top5_ao_fisher",
        phase="csta_ao_pia",
        family="csta_pia",
        method_type="csta_internal",
        source_space="covariance_template",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="_run_csta_method + run_act_pilot.py",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms csta_topk_uniform_top5_ao_fisher",
        notes="AO-PIA Fisher direction bank: within-class vs between-class scatter eigen directions.",
    ),
    "csta_topk_uniform_top5_ao_contrastive": ExternalBaselineSpec(
        name="csta_topk_uniform_top5_ao_contrastive",
        phase="csta_ao_pia",
        family="csta_pia",
        method_type="csta_internal",
        source_space="covariance_template",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="_run_csta_method + run_act_pilot.py",
        code_file="scripts/run_external_baselines_phase1.py",
        runner="run_external_baselines_phase1.py --arms csta_topk_uniform_top5_ao_contrastive",
        notes="AO-PIA Contrastive direction bank: within+positive vs between+negative scatter eigen directions.",
    ),
    "ag_target_direct": ExternalBaselineSpec(
        name="ag_target_direct",
        phase="csta_ag_pia",
        family="ag_pia",
        method_type="csta_internal",
        source_space="covariance_state_operator",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta_debug",
        code_symbol="core.csta.ag_pia.build_ag_pia_aug_out",
        code_file="core/csta/ag_pia.py",
        runner="run_external_baselines_phase1.py --arms ag_target_direct",
        notes="Debug-only AG-PIA target-field direct direction; not a paper baseline.",
    ),
    "ag_pia_single": ExternalBaselineSpec(
        name="ag_pia_single",
        phase="csta_ag_pia",
        family="ag_pia",
        method_type="csta_internal",
        source_space="covariance_state_operator",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="core.csta.ag_pia.build_ag_pia_aug_out",
        code_file="core/csta/ag_pia.py",
        runner="run_external_baselines_phase1.py --arms ag_pia_single",
        notes="AG-PIA single-head augmentation-field generalized inverse operator.",
    ),
    "ag_pia_multihead5": ExternalBaselineSpec(
        name="ag_pia_multihead5",
        phase="csta_ag_pia",
        family="ag_pia",
        method_type="csta_internal",
        source_space="covariance_state_operator",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="core.csta.ag_pia.build_ag_pia_aug_out",
        code_file="core/csta/ag_pia.py",
        runner="run_external_baselines_phase1.py --arms ag_pia_multihead5",
        notes="AG-PIA five-head operator with uniform head sampling.",
    ),
    "cs_flow_target_direct": ExternalBaselineSpec(
        name="cs_flow_target_direct",
        phase="csta_cs_flow",
        family="cs_flow",
        method_type="csta_internal",
        source_space="covariance_state_flow",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta_debug",
        code_symbol="core.csta.cs_flow.build_cs_flow_aug_out",
        code_file="core/csta/cs_flow.py",
        runner="run_external_baselines_phase1.py --arms cs_flow_target_direct",
        notes="Debug-only CS-Flow target velocity probe; not a competing paper baseline.",
    ),
    "cs_flow_single_step": ExternalBaselineSpec(
        name="cs_flow_single_step",
        phase="csta_cs_flow",
        family="cs_flow",
        method_type="csta_internal",
        source_space="covariance_state_flow",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="core.csta.cs_flow.build_cs_flow_aug_out",
        code_file="core/csta/cs_flow.py",
        runner="run_external_baselines_phase1.py --arms cs_flow_single_step",
        notes="One-step covariance-state flow matching direction operator.",
    ),
    "latent_residual_direct": ExternalBaselineSpec(
        name="latent_residual_direct",
        phase="csta_latent_residual_flow",
        family="latent_residual_flow",
        method_type="csta_internal",
        source_space="covariance_state_latent_residual",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta_debug",
        code_symbol="core.csta.latent_residual_flow.build_latent_residual_aug_out",
        code_file="core/csta/latent_residual_flow.py",
        runner="run_external_baselines_phase1.py --arms latent_residual_direct",
        notes="Debug-only direct same-class RBF residual sampler; not a competing paper baseline.",
    ),
    "latent_residual_flow": ExternalBaselineSpec(
        name="latent_residual_flow",
        phase="csta_latent_residual_flow",
        family="latent_residual_flow",
        method_type="csta_internal",
        source_space="covariance_state_latent_residual",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="core.csta.latent_residual_flow.build_latent_residual_aug_out",
        code_file="core/csta/latent_residual_flow.py",
        runner="run_external_baselines_phase1.py --arms latent_residual_flow",
        notes="Continuous latent residual distribution generator with MSE+cosine residual transport loss.",
    ),
    "task_guided_residual_direct": ExternalBaselineSpec(
        name="task_guided_residual_direct",
        phase="csta_task_guided_latent_residual",
        family="task_guided_latent_residual_flow",
        method_type="csta_internal",
        source_space="covariance_state_task_guided_latent_residual",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta_debug",
        code_symbol="core.csta.task_guided_latent_residual_flow.build_task_guided_latent_aug_out",
        code_file="core/csta/task_guided_latent_residual_flow.py",
        runner="run_external_baselines_phase1.py --arms task_guided_residual_direct",
        notes="Debug-only direct sampler from task-reweighted residual distribution; not a paper baseline.",
    ),
    "task_guided_latent_residual_flow": ExternalBaselineSpec(
        name="task_guided_latent_residual_flow",
        phase="csta_task_guided_latent_residual",
        family="task_guided_latent_residual_flow",
        method_type="csta_internal",
        source_space="covariance_state_task_guided_latent_residual",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="core.csta.task_guided_latent_residual_flow.build_task_guided_latent_aug_out",
        code_file="core/csta/task_guided_latent_residual_flow.py",
        runner="run_external_baselines_phase1.py --arms task_guided_latent_residual_flow",
        notes="Latent residual generator trained on warm-up task-utility-reweighted residual targets.",
    ),
    "lc_residual_direct": ExternalBaselineSpec(
        name="lc_residual_direct",
        phase="csta_lc_latent_residual",
        family="label_consistent_latent_residual_flow",
        method_type="csta_internal",
        source_space="covariance_state_label_consistent_latent_residual",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta_debug",
        code_symbol="core.csta.lc_latent_residual_flow.build_lc_latent_aug_out",
        code_file="core/csta/lc_latent_residual_flow.py",
        runner="run_external_baselines_phase1.py --arms lc_residual_direct",
        notes="Debug-only direct sampler from label-consistent boundary-reweighted residual distribution.",
    ),
    "lc_latent_residual_flow": ExternalBaselineSpec(
        name="lc_latent_residual_flow",
        phase="csta_lc_latent_residual",
        family="label_consistent_latent_residual_flow",
        method_type="csta_internal",
        source_space="covariance_state_label_consistent_latent_residual",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="core.csta.lc_latent_residual_flow.build_lc_latent_aug_out",
        code_file="core/csta/lc_latent_residual_flow.py",
        runner="run_external_baselines_phase1.py --arms lc_latent_residual_flow",
        notes="Latent residual generator trained on label-consistent boundary-band residual targets.",
    ),
    "spg_pia_zhead": ExternalBaselineSpec(
        name="spg_pia_zhead",
        phase="csta_spg_pia_zhead",
        family="spg_pia",
        method_type="csta_internal",
        source_space="covariance_state_support_projected_gradient",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="core.csta.spg_pia.build_spg_pia_aug_out",
        code_file="core/csta/spg_pia.py",
        runner="run_external_baselines_phase1.py --arms spg_pia_zhead",
        notes="Support-projected z-head task gradient operator with stochastic support-space smoothing.",
    ),
    "spg_pia_zhead_deterministic": ExternalBaselineSpec(
        name="spg_pia_zhead_deterministic",
        phase="csta_spg_pia_zhead",
        family="spg_pia",
        method_type="csta_internal",
        source_space="covariance_state_support_projected_gradient",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta_debug",
        code_symbol="core.csta.spg_pia.build_spg_pia_aug_out",
        code_file="core/csta/spg_pia.py",
        runner="run_external_baselines_phase1.py --arms spg_pia_zhead_deterministic",
        notes="Debug-only deterministic repeated support-projected gradient direction.",
    ),
    "ecl_spg_pia_zhead": ExternalBaselineSpec(
        name="ecl_spg_pia_zhead",
        phase="csta_ecl_spg_pia",
        family="ecl_spg_pia",
        method_type="csta_internal",
        source_space="covariance_state_energy_calibrated_langevin_spg",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="core.csta.spg_pia.build_spg_pia_aug_out",
        code_file="core/csta/spg_pia.py",
        runner="run_external_baselines_phase1.py --arms ecl_spg_pia_zhead",
        notes="Energy-calibrated Langevin support-projected gradient operator.",
    ),
    "ecl_spg_pia_zhead_deterministic": ExternalBaselineSpec(
        name="ecl_spg_pia_zhead_deterministic",
        phase="csta_ecl_spg_pia",
        family="ecl_spg_pia",
        method_type="csta_internal",
        source_space="covariance_state_energy_calibrated_langevin_spg",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta_debug",
        code_symbol="core.csta.spg_pia.build_spg_pia_aug_out",
        code_file="core/csta/spg_pia.py",
        runner="run_external_baselines_phase1.py --arms ecl_spg_pia_zhead_deterministic",
        notes="Debug-only deterministic reference for ECL-SPG-PIA.",
    ),
    "rn_ecl_spg_pia_zhead": ExternalBaselineSpec(
        name="rn_ecl_spg_pia_zhead",
        phase="csta_rn_ecl_spg_pia",
        family="rn_ecl_spg_pia",
        method_type="csta_internal",
        source_space="covariance_state_rank_normalized_ecl_spg",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta",
        code_symbol="core.csta.spg_pia.build_spg_pia_aug_out",
        code_file="core/csta/spg_pia.py",
        runner="run_external_baselines_phase1.py --arms rn_ecl_spg_pia_zhead",
        notes="Rank-normalized ECL support-projected gradient operator.",
    ),
    "rn_ecl_spg_pia_zhead_deterministic": ExternalBaselineSpec(
        name="rn_ecl_spg_pia_zhead_deterministic",
        phase="csta_rn_ecl_spg_pia",
        family="rn_ecl_spg_pia",
        method_type="csta_internal",
        source_space="covariance_state_rank_normalized_ecl_spg",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta_debug",
        code_symbol="core.csta.spg_pia.build_spg_pia_aug_out",
        code_file="core/csta/spg_pia.py",
        runner="run_external_baselines_phase1.py --arms rn_ecl_spg_pia_zhead_deterministic",
        notes="Debug-only deterministic reference for RN-ECL-SPG-PIA.",
    ),
    "spg_cfm_one_step": ExternalBaselineSpec(
        name="spg_cfm_one_step",
        phase="csta_spg_cfm",
        family="spg_cfm",
        method_type="csta_internal",
        source_space="covariance_state_spg_conditioned_cfm",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta_future_branch",
        code_symbol="core.csta.spg_cfm.build_spg_cfm_aug_out",
        code_file="core/csta/spg_cfm.py",
        runner="run_external_baselines_phase1.py --arms spg_cfm_one_step",
        notes="Future-branch mechanism: support-projected gradient conditioned one-step CFM.",
    ),
    "spg_cfm_align_one_step": ExternalBaselineSpec(
        name="spg_cfm_align_one_step",
        phase="csta_spg_cfm",
        family="spg_cfm",
        method_type="csta_internal",
        source_space="covariance_state_spg_conditioned_cfm",
        label_mode="hard",
        budget_matched=True,
        implementation_status="native_csta_future_branch",
        code_symbol="core.csta.spg_cfm.build_spg_cfm_aug_out",
        code_file="core/csta/spg_cfm.py",
        runner="run_external_baselines_phase1.py --arms spg_cfm_align_one_step",
        notes="Future-branch mechanism: SPG-conditioned CFM with alignment regularization.",
    ),
    "manifold_mixup": ExternalBaselineSpec(
        name="manifold_mixup",
        phase="phase3",
        family="hidden_state",
        method_type="external_baseline",
        source_space="hidden_state",
        label_mode="soft",
        budget_matched=False,
        implementation_status="native_training_strategy",
        code_symbol="fit_manifold_mixup_backbone",
        code_file="utils/backbone_trainers.py",
        runner="run_external_baselines_phase1.py --arms manifold_mixup",
        notes="Hidden-state Mixup training strategy; ResNet1D only.",
    ),
    "timevae_classwise_optional": ExternalBaselineSpec(
        name="timevae_classwise_optional",
        phase="phase3",
        family="generative_model",
        method_type="external_baseline",
        source_space="generative_model",
        label_mode="hard",
        budget_matched=False,
        implementation_status="pytorch_translation_adapter",
        code_symbol="timevae_classwise_optional",
        code_file="utils/external_baseline_methods/timevae.py",
        runner="run_external_baselines_phase1.py --arms timevae_classwise_optional",
        notes="Classwise TimeVAE-style generator; records target/actual ratio and is not yet full official TimeVAE parity.",
    ),
    "timegan_classwise": ExternalBaselineSpec(
        name="timegan_classwise",
        phase="phase3",
        family="generative_model",
        method_type="external_baseline",
        source_space="generative_model",
        label_mode="hard",
        budget_matched=True,
        implementation_status="pytorch_timegan_style_adapter",
        code_symbol="timegan_classwise",
        code_file="utils/external_baseline_methods/timegan.py",
        runner="run_external_baselines_phase1.py --arms timegan_classwise",
        notes="Classwise TimeGAN-style PyTorch adapter; not official TensorFlow author-code parity.",
    ),
    "diffusionts_classwise": ExternalBaselineSpec(
        name="diffusionts_classwise",
        phase="phase3",
        family="generative_model",
        method_type="external_baseline",
        source_space="generative_model",
        label_mode="hard",
        budget_matched=True,
        implementation_status="external_official_adapter",
        code_symbol="diffusionts_classwise",
        code_file="utils/external_baseline_methods/diffusionts.py",
        runner="run_external_baselines_phase1.py --arms diffusionts_classwise",
        notes="Classwise Diffusion-TS generator with classifier guidance (ICLR 2024).",
    ),
    "timevqvae_classwise": ExternalBaselineSpec(
        name="timevqvae_classwise",
        phase="phase3",
        family="generative_model",
        method_type="external_baseline",
        source_space="generative_model",
        label_mode="hard",
        budget_matched=True,
        implementation_status="external_official_adapter",
        code_symbol="timevqvae_classwise",
        code_file="utils/external_baseline_methods/timevqvae.py",
        runner="run_external_baselines_phase1.py --arms timevqvae_classwise",
        notes="Classwise TimeVQVAE generator (AISTATS 2023).",
    ),
}


def _apply_runtime_registry(spec: ExternalBaselineSpec) -> ExternalBaselineSpec:
    """Overlay fields owned by the runtime registry onto a documentation spec."""
    info = METHOD_INFO.get(spec.name)
    if info is None:
        raise KeyError(f"Manifest entry {spec.name!r} is missing from external_runner_registry.METHOD_INFO.")
    return replace(
        spec,
        source_space=info.source_space,
        label_mode=info.label_mode,
        budget_matched=info.budget_matched,
    )


EXTERNAL_BASELINE_CATALOG = {
    name: _apply_runtime_registry(spec)
    for name, spec in EXTERNAL_BASELINE_CATALOG.items()
}


def validate_catalog_against_runtime_registry() -> None:
    missing = sorted(set(EXTERNAL_BASELINE_CATALOG) - set(METHOD_INFO))
    if missing:
        raise KeyError(f"Manifest methods missing from runtime registry: {missing}")


def catalog_rows() -> List[ExternalBaselineSpec]:
    return [EXTERNAL_BASELINE_CATALOG[name] for name in sorted(EXTERNAL_BASELINE_CATALOG)]


def names_by_phase(phase: str) -> List[str]:
    return sorted(name for name, spec in EXTERNAL_BASELINE_CATALOG.items() if spec.phase == phase)


def names_by_family(family: str) -> List[str]:
    return sorted(name for name, spec in EXTERNAL_BASELINE_CATALOG.items() if spec.family == family)


# ── Method type filters (added 2026-05-05) ─────────────────────────────

def external_baselines_only() -> List[ExternalBaselineSpec]:
    """Return only true external baseline methods (not CSTA internal or controls)."""
    return [s for s in catalog_rows() if s.method_type == "external_baseline"]


def csta_methods() -> List[ExternalBaselineSpec]:
    """Return CSTA internal method variants."""
    return [s for s in catalog_rows() if s.method_type == "csta_internal"]


def csta_controls() -> List[ExternalBaselineSpec]:
    """Return CSTA control baselines (no_aug, random_cov, pca_cov)."""
    return [s for s in catalog_rows() if s.method_type == "csta_control"]


def is_external_baseline(name: str) -> bool:
    spec = EXTERNAL_BASELINE_CATALOG.get(name)
    return spec is not None and spec.method_type == "external_baseline"


def is_csta_method(name: str) -> bool:
    spec = EXTERNAL_BASELINE_CATALOG.get(name)
    return spec is not None and spec.method_type in ("csta_internal", "csta_control")
