#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
scripts/run_phase13a_seed0.py

Phase 13A: Evidence Chain Hardening (Seed 0)
1. Run Manifold Training (Guided p=2.0, Seed 0) -> Export canonical CSV (phase13/seed0).
2. Run Spatial Export (Inference on Validation Set using existing Checkpoint) -> Export canonical CSV.
3. Run Fusion (V0, V1) -> Export Summary.
4. Validate Artifacts.
"""

import sys
import os
import torch
import shutil
import json
import numpy as np
import pandas as pd

# Add project root to sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from datasets.adapters import get_adapter
from runners.manifold_deep_runner import ManifoldDeepRunner
from runners.spatial_dcnet_torch import SpatialDCNetRunnerTorch, DCNetTorch
from scripts.fusion_postprocess import run_fusion

# Define Paths
BASE_DIR = "promoted_results/phase13/seed0"
SPATIAL_PRED_PATH = os.path.join(BASE_DIR, "spatial_trial_pred.csv") 
MANIFOLD_PRED_PATH = os.path.join(BASE_DIR, "manifold_trial_pred_guided_p2.csv")

def ensure_dir(path):
    if not os.path.exists(path):
        os.makedirs(path, exist_ok=True)

def run_manifold_seed0(adapter):
    print("\n=== [1/3] Manifold Stream (Guided p=2.0) ===")
    
    # Args
    class Args:
        torch_device = "cuda" if torch.cuda.is_available() else "cpu"
        epochs = 50
        batch_size = 32
        mvp1_guided_cov = True
        mvp1_attn_power = 2.0
        # Use Seed 0
        seed = 0
        # Use the checkpoint generated by the Spatial Fallback step
        dcnet_ckpt = "experiments/checkpoints/seedv_spatial_torch_seed0_phase13a_spatial_fallback.pt"
        metrics_csv = None
        cov_alpha = 0.01
        hidden_dim = 96
        
    args = Args()
    
    # Validate Checkpoint
    if not os.path.exists(args.dcnet_ckpt):
         # Try original fallback
         if os.path.exists("experiments/checkpoints/seed0_dcnet_refactor.pt"):
              args.dcnet_ckpt = "experiments/checkpoints/seed0_dcnet_refactor.pt"
         else:
              raise FileNotFoundError(f"Teacher Checkpoint missing: {args.dcnet_ckpt}")
             
    folds = adapter.get_manifold_trial_folds()
    runner = ManifoldDeepRunner(args, num_classes=3)
    
    # Run
    # Note: Manifold runner currently exports to `promoted_results/{fold_name}...`
    # We will let it run, then MOVE the file to `phase13/seed0/`.
    fold_name = "phase13a_seed0_guided"
    res = runner.fit_predict(folds['fold1'], fold_name=fold_name)
    
    # Move Artifacts
    src_csv = f"promoted_results/{fold_name}_preds_test_last_trial.csv"
    if os.path.exists(src_csv):
        shutil.copy(src_csv, MANIFOLD_PRED_PATH)
        print(f"Manifold Preds saved to: {MANIFOLD_PRED_PATH}")
    else:
        raise FileNotFoundError(f"Manifold runner did not produce: {src_csv}")
        
    # Export Meta
    meta = {
        "seed": 0,
        "guided": True,
        "power": 2.0,
        "epochs": 50,
        "test_trial_acc": res['last']['test_trial_acc']
    }
    with open(os.path.join(BASE_DIR, "export_meta.json"), "w") as f:
        json.dump(meta, f, indent=2)

def run_spatial_export_seed0(adapter):
    print("\n=== [2/3] Spatial Stream Export ===")
    # We need to run inference using Spatial Runner to generate the Trial-Level CSV with entropy/margin.
    # We can reuse `fit_predict`, but maybe just evaluation?
    # `fit_predict` re-trains unless we handle it carefully.
    # Actually, `SpatialDCNetRunnerTorch` (Phase 9) implementation:
    # `fit_predict` logic:
    # 1. Load Data.
    # 2. Init Model.
    # 3. If `checkpoint` provided, load it?
    # Checking `spatial_dcnet_torch.py`:
    # It has `checkpoint_prefix`. If present, it might load?
    # No, `fit_predict` calls `model.apply(init_weights)` then trains loop.
    # UNLESS we hack it or add an Inference Mode.
    # BUT, we have `experiments/phase9_fusion/preds/spatial_trial_preds_seed0.csv` from previous runs?
    # Do those have entropy/margin? No, I just added the code.
    # So I MUST RE-RUN INFERENCE (or Training).
    # Re-training might shift results slightly due to randomness if not perfectly seeded?
    # Better to Load Checkpoint and Evaluate.
    # But `SpatialDCNetRunnerTorch` doesn't expose a clean `evaluate` method for external call easily.
    # It's better to modify `fit_predict` to skip training if `checkpoint` is loaded?
    # Or just run it. It's fast (CNN).
    # "Usable Spatial checkpoint (DCNet) exists".
    # I will modify the call to `fit_predict` to use 0 epochs if I can load weights?
    # Or just rely on previous training if "Usable" implies "Use existing file"?
    # User said: "Spatial export (trial-level): Aggregate ... using same policy".
    # And "Standardize ... outputs".
    # Since I just added entropy/margin to the code, I MUST execute the code.
    # If I cannot load weights easily, I might have to re-train (Seed 0 is deterministic).
    # Let's check `run_phase9_8_refactor.py`.
    # It sets seed.
    
    # Let's try to run 0 epochs?
    
    class Args:
        epochs = 0 # Skip training loop?
        batch_size = 32
        lr = 1e-3
        seed = 0
        device = "cuda" if torch.cuda.is_available() else "cpu"
        
    # Data
    # Spatial runner needs `get_spatial_folds_for_cnn`.
    folds = adapter.get_spatial_folds_for_cnn(
        seed_de_root="data/SEED/SEED_EEG/ExtractedFeatures_1s",
        seed_de_var="de_LDS1"
    )
    
    # We need to load the checkpoint MANUALLY if epochs=0.
    # Because `fit_predict` won't load it by default (it inits new model).
    # Actually, `fit_predict` returns `result`.
    # I should instantiate the runner, Init model, Load state_dict, then call internal `batched_logits`?
    # Or cleaner: Modify `fit_predict` to verify "if epochs==0, try load checkpoint_prefix".
    # I will do manual loading + eval via Runner internals if possible.
    
    ckpt_path = "experiments/checkpoints/seedv_spatial_torch_seed0_phase13a_spatial_fallback.pt"
    if not os.path.exists(ckpt_path):
         ckpt_path = "experiments/checkpoints/seed0_dcnet_refactor.pt"
         
    if not os.path.exists(ckpt_path):
        print("CRITICAL: Spatial Checkpoint missing. Re-training (Fast).")
        # Set epochs = 50
        Args.epochs = 50
        load_ckpt = False
    else:
        print(f"Loading Spatial Checkpoint: {ckpt_path}")
        load_ckpt = True
        
    runner = SpatialDCNetRunnerTorch(
        num_classes=3,
        epochs=Args.epochs,
        batch_size=Args.batch_size,
        learning_rate=Args.lr,
        device=Args.device,
        spatial_head="softmax"
    )
    
    # Hack: Inject checkpoint load into runner or subclass?
    # Or just run it?
    # If I pass `checkpoint_prefix` maybe? The class doesn't seem to use it for loading.
    # Let's modify `fit_predict` in-flight? No.
    # I will manually run the Eval logic using the runner's methods.
    
    X_tr, y_tr, tid_tr = folds['fold1'].X_train, folds['fold1'].y_train.ravel(), folds['fold1'].trial_id_train
    X_te, y_te, tid_te = folds['fold1'].X_test, folds['fold1'].y_test.ravel(), folds['fold1'].trial_id_test
    
    if load_ckpt:
        model = DCNetTorch(310, 3).to(Args.device)
        checkpoint = torch.load(ckpt_path, map_location=Args.device)
        if "model_state" in checkpoint:
            model.load_state_dict(checkpoint["model_state"])
        else:
            model.load_state_dict(checkpoint)
        
        # Inference Logic (Manual)
        X_te_tensor = torch.from_numpy(X_te).float().reshape(-1, 310, 1, 1)
        logits_te = runner._batched_logits(model, X_te_tensor, torch.device(Args.device), Args.batch_size)
        proba_test = torch.softmax(torch.from_numpy(logits_te), dim=1).numpy()
    else:
        # Fallback Training
        print("Training Spatial Model from Scratch (Fallback)...")
        # Ensure we set seed again to be safe
        torch.manual_seed(Args.seed)
        np.random.seed(Args.seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(Args.seed)
            
        res = runner.fit_predict(folds['fold1'], fold_name=f"seed{Args.seed}_phase13a_spatial_fallback")
        proba_test = res['sample_proba_test']
        # Note: fit_predict usually saves checkpoint too.
        # We should save it to the expected path to avoid re-training next time?
        if hasattr(runner, 'model'):
             torch.save(runner.model.state_dict(), ckpt_path)
             print(f"Saved Fallback Checkpoint to: {ckpt_path}")
    
    # Export Logic (Shared)
    print("Running Export...")
    
    df_te = pd.DataFrame({
        "trial_id": tid_te,
        "true_label": y_te,
        "prob_0": proba_test[:, 0],
        "prob_1": proba_test[:, 1],
        "prob_2": proba_test[:, 2]
    })
    
    # Aggregate
    agg = df_te.groupby("trial_id").agg({
        "true_label": "first",
        "prob_0": "mean",
        "prob_1": "mean",
        "prob_2": "mean",
        "trial_id": "count"
    }).rename(columns={"trial_id": "n_windows"}).reset_index()
    
    agg["pred_label"] = np.argmax(agg[["prob_0", "prob_1", "prob_2"]].values, axis=1)
    
    # Entropy & Margin
    probs = agg[["prob_0", "prob_1", "prob_2"]].values
    p_safe = np.clip(probs, 1e-9, 1.0)
    agg["entropy"] = -np.sum(p_safe * np.log(p_safe), axis=1)
    p_sorted = np.sort(probs, axis=1)
    agg["margin"] = p_sorted[:, -1] - p_sorted[:, -2]
    agg["seed"] = 0
    
    # Save
    cols = ["seed", "true_label", "n_windows", "prob_0", "prob_1", "prob_2", "pred_label", "entropy", "margin", "trial_id"]
    agg.to_csv(SPATIAL_PRED_PATH, columns=cols, index=False)
    print(f"Spatial Preds exported to: {SPATIAL_PRED_PATH}")

def main():
    ensure_dir(BASE_DIR)
    
    # Load Adapter
    adapter = get_adapter("seed1")
    
    # 1. Spatial (Generates Checkpoint if missing + Export)
    run_spatial_export_seed0(adapter)
    
    # 2. Manifold (Uses Checkpoint from Step 1)
    run_manifold_seed0(adapter)
    
    # 3. Fusion
    print("\n=== [3/3] Fusion ===")
    run_fusion(SPATIAL_PRED_PATH, MANIFOLD_PRED_PATH, BASE_DIR, seed=0)
    
    # 4. Copy Split JSON
    # We can get split info from manifold runner output or adapter?
    # Manifold runner doesn't export split.json explicitly?
    # It does check intersection.
    # Let's create `promoted_results/phase13/seed0/split.json` manually if needed or copy from Phase 11 artifacts if they are trusted.
    # Phase 11 had `seed0...split.json`.
    src_split = "promoted_results/seed0_fold1_quick_check_split.json" # from prev step?
    # Or just rely on summary.
    
    print("\n=== Phase 13A Seed 0 Complete ===")
    print(f"Check results in: {BASE_DIR}")

if __name__ == "__main__":
    main()
